0022-non-required-derivative-generation-in-sdr
sul-dlss-labs/engineering-design-adrs pull request #46
Opened 2024-03-27 18:06 UTC by peetucket

ADR 0022 for non-required derivative generation (OCR/transcription)

2024-03-27 18:23 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +Automated OCR (from images/PDFs) and transcription (from video/audio) are desired for a subset of content deposited in SDR in order to improve accessibility and discoverability.  Current processes fo
We could consider including links to relevant documentation here too:

* https://docs.google.com/document/d/1vzDFaD9BKmyDaJdXcVIp82Vd2BJ9hnuUH1KhXilEOWk/edit
* https://docs.google.com/document/d/10MzjOjwmuijHD5rgO5QxxuLKFwv94Lq29vDy0Y_xDUg/edit

2024-03-27 18:24 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* Workflow driven solution
Should we include brief blurbs explaining why we rejected "option 1" and "option 2" from Andrew's original doc?

2024-03-27 18:36 UTC, jcoyne commented on 0022-derivative-generation.md
> +Automated OCR (from images/PDFs) and transcription (from video/audio) are desired for a subset of content deposited in SDR in order to improve accessibility and discoverability.  Current processes fo
I think using "non-required" is confusing and I'd opt for this to be left out.  It is my understanding that transcription is in fact required for videos to be accessible.

2024-03-27 20:05 UTC, jcoyne commented on 0022-derivative-generation.md
> +Automated OCR (from images/PDFs) and transcription (from video/audio) are desired for a subset of content deposited in SDR in order to improve accessibility and discoverability.  Current processes fo
I think "text extraction" is the most clear and "non-image derivative" is okay too.

2024-03-27 20:10 UTC, peetucket commented on 0022-derivative-generation.md
> +* Workflow driven solution
Added

2024-03-27 20:10 UTC, peetucket commented on 0022-derivative-generation.md
> +Automated OCR (from images/PDFs) and transcription (from video/audio) are desired for a subset of content deposited in SDR in order to improve accessibility and discoverability.  Current processes fo
Adjusted text to remove "required" vs "non-required" and added more explanation about what is meant.

2024-03-28 18:57 UTC, jcoyne requested changes

2024-03-28 18:57 UTC, jcoyne commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and use logic (TBD) to create the new workflow for that object if
Why don't we just add steps for this at the end of the accessioningWF after pushing to preservation.   If we're just going to start a new version anyway, we're still going to potentially violate the: "Generation of non-image derivatives should not delay accessioning." as nobody else can do anything until that version is closed.

2024-03-28 18:57 UTC, jcoyne commented on 0022-derivative-generation.md
> +* The new workflow will have steps to run OCR, transcription and possible pause for review (if needed).
What will determine this need?

2024-03-28 18:57 UTC, jcoyne commented on 0022-derivative-generation.md
> +After considering the pros and cons of each approach, a form of option 3 was selected, and is described here.  The deficiencies of option 1 and 2 that led to this option are summarized in the above d
Please pull the reasons into this document.  the google docs are restricted to a much smaller audience.

2024-03-28 19:41 UTC, peetucket commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and use logic (TBD) to create the new workflow for that object if
I see...so basically new steps in accessionWF instead of a new workflow.

Either way, I think we will block people from opening new versions (either because the current version is still open, waiting for derivatives in accessionWF to finish or the because the new version is opened waiting for derivatives to finish in the new workflow).

I could see some pros/cons for each approach.

2024-03-28 19:42 UTC, peetucket commented on 0022-derivative-generation.md
> +* The new workflow will have steps to run OCR, transcription and possible pause for review (if needed).
Will add a note.  I believe the current requirement is that the accessioneer will have to indicate this ahead of time (and thus will need to pass this choice own through the workflow)

2024-03-28 19:49 UTC, peetucket commented on 0022-derivative-generation.md
> +After considering the pros and cons of each approach, a form of option 3 was selected, and is described here.  The deficiencies of option 1 and 2 that led to this option are summarized in the above d
added the primary reason (one of the requirements make it the only option)

2024-03-28 21:26 UTC, jcoyne commented on 0022-derivative-generation.md
> +* The new workflow will have steps to run OCR, transcription and possible pause for review (if needed).
In pre-assembly?

2024-03-29 17:49 UTC, peetucket commented on 0022-derivative-generation.md
> +* The new workflow will have steps to run OCR, transcription and possible pause for review (if needed).
Yes, most likely spot. Will note.

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +This propsal addresses so called "non-image" derivatives (though they may be referred to simply as "derivatives" throughout this ADR).  For the purpose of this ADR, "non-image" derivatives are define
"proposal" instead of "propsal".

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +This distinction is useful because some derivatives must be generated during accessioning, while others may be genereated after accessioning.
"generated" instead of "genereated".

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +After considering the pros and cons of each approach, option 3 was selected, and is described here.  The pros and cons of the vairous options are summarized in the above document, and the reason opti
"various" instead of "vairous".

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
Currently, we create optionally dissemination workflows as the last step of the accession workflow. I don't see any compelling reason to deviate from that practice. The use of messaging here doesn't buy us anything.

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* The OCR will be peformed by ABBYY, and the transcription will be peformed by Whipser.  These services are likely to be run separately from the server(s) monitoring for `end-accession.completed` and
"Whisper" instead of "Whipser".

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* As part of the workflow, the object will be opened, and then closed when OCR and transcrption is complete to ensure files are preserved.
"transcription" instead of "transcrption".

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* The OCR will be peformed by ABBYY, and the transcription will be peformed by Whipser.  These services are likely to be run separately from the server(s) monitoring for `end-accession.completed` and
"include" instead of "inclue".

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
The object will need to be opened before creating the OCR/captioning assembly workflow. This can be accomplished by calling DSA's accession endpoint to start the OCR/captioning assembly workflow.

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* The new workflow will have consist of several steps, which will inclue any required versioning, OCR and transcription, and possible pause of review.  If review is required, it will be indicated by
Versioning should be performed outside the workflow.

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* The new workflow will have consist of several steps, which will inclue any required versioning, OCR and transcription, and possible pause of review.  If review is required, it will be indicated by
The the OCR/captioning assembly workflow should either start an assembly workflow or close the version (to start accessioning).

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +* Closing the object will trigger assemblyWF, which will ensure the files are properly shelved and preserved.
"accessionWF" not "assemblyWF"

2024-03-29 20:33 UTC, justinlittman commented on 0022-derivative-generation.md
> +Implementation Details:
I'd remove these Implementation Details. They're not likely to be right and are more appropriate as WC working docs.

2024-03-29 21:19 UTC, peetucket commented on 0022-derivative-generation.md
> +* The new workflow will have consist of several steps, which will inclue any required versioning, OCR and transcription, and possible pause of review.  If review is required, it will be indicated by
I'd like to understand better which process is doing the versioning in this case.

2024-03-29 22:41 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
@justinlittman @peetucket Could/should the `EndAccession` robot make the determination roughly [here](https://github.com/sul-dlss/common-accessioning/blob/main/lib/robots/dor_repo/accession/end_accession.rb#L14-L34) whether the object needs a post-accessioning workflow (one of the new text extraction assembly workflows), either based on the Cocina or a workflow variable? I don't believe the WAS dissemination WF code here tends to hang up accessioning?

2024-04-01 12:53 UTC, edsu commented on 0022-derivative-generation.md
> +* Option 3 had derivatives generated after accessioning
I don't know if it's worth mentioning here, but as a thought experiment we also briefly considered not using SDR workflows for text extraction, and to do it in the access portfolio after content is delivered:

https://docs.google.com/document/d/1EDcj-lb2jpjzMxm2MDsvVvpYOopvsgtRUrY97arzcu4/edit#heading=h.j58qbs1p9lqa

2024-04-01 13:36 UTC, edsu commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
Is it the case that if we kick off the new workflow at the end of accession WF the text derivatives will be part of the same version? Then, if something goes wrong during text extraction, an Argo user will see the one version they initiated, and it will be stuck? This seems like something we want to avoid.

2024-04-01 13:41 UTC, edsu commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
As @mjgiarlo was suggesting, I'm also wondering if we will want to have two new workflows, one for each type of job: ocrWF, transcriptionWF.

2024-04-01 15:30 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
@edsu 💬 
> Is it the case that if we kick off the new workflow at the end of accession WF the text derivatives will be part of the same version? 

If it runs after the accessioning workflow's `end-accessioning` step, the version should be closed at that time.

2024-04-01 15:32 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
@edsu 💬 
> As I think @mjgiarlo might have been suggesting, is there value in having two new workflows, instead of one? So instead of one `textExtractionWF` there would be `ocrWF` and `transcribeWF`.

I don't *think* I can take credit for the idea of using type-specific derivative generation workflows. I believe that's from [@justinlittman's straw-person proposal](https://docs.google.com/document/d/1JLJwio7xVDDh75KY3dZJIFPDep-92hoQJ5p9EgFKabY/edit#heading=h.nc2q89vu9te)

2024-04-01 15:34 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* Option 3 had derivatives generated after accessioning
I'd like to see ☝🏻 included in the ADR for sure. Good call.

2024-04-01 15:37 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
@peetucket 💬 
> So there are new steps in accessionWF that decide if OCR/transcription is needed, and if so, they start the new workflow? But allow accessionWF to complete (thus not blocking accessioning)?

The "special dissemination workflow" code we have in place kicks off as part of the `end-accessioning` step of the accessioning workflow, so it's essentially already done at that point and the dissemination workflow kicks off next.

> Won't this cause potential race conditions with the new workflow being unable to open the object until accessioning is done?

We haven't seen that with the diss. WFs before, I don't think.

2024-04-01 15:38 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +* The new workflow will have consist of several steps, which will inclue any required versioning, OCR and transcription, and possible pause of review.  If review is required, it will be indicated by
@justinlittman @peetucket This sounds ripe for discussion this morning.

2024-04-01 22:08 UTC, peetucket commented on 0022-derivative-generation.md
> +* When accessioning is complete, an `end-accession.completed` message is currently sent.  A new service will look for these messages and [use logic](https://docs.google.com/document/d/1JLJwio7xVDDh75
Updated ADR to add the `end-accession` workflow idea.  Moved messaging based workflow triggering an alternative section.

2024-04-01 22:08 UTC, peetucket commented on 0022-derivative-generation.md
> +* Option 3 had derivatives generated after accessioning
Added

2024-04-02 22:35 UTC, mjgiarlo commented on 0022-derivative-generation.md
> +  * ...
Consider adding:

```suggestion
  * Recommended: 2024-04-01
```

2024-04-02 22:59 UTC, mjgiarlo approved these changes

2024-04-02 23:00 UTC, merged